!Config
org: dc=myorg,dc=company,dc=com
ldap_secret: /etc/ldap.secret
ldap_uri: ldap://ldapserver.company.com
people: ou=employees,dc=myorg,dc=company,dc=com
admin: cn=admin,dc=myorg,dc=company,dc=com
groups: ou=groups,dc=myorg,dc=company,dc=com
timeout: 60